### ISSUE TITLE
CRITICAL: Instance variables not initialized in constructor

### ISSUE THREAD

**Issue by radams78** [samibr96/lab2#18]
The variables Angle, truck and ramp are not initialized in the constructor, and so therefore calling raisePlatform or lowerPlatform on an object of type Scania will throw an exception.

Hint: remove the variable truck. Scania should be a subclass of Truck, not delegate to it.

https://github.com/samibr96/lab2/blob/f7484a73a8caca54263d3309d8887adbb0e6a4e1/Scania.java#L16-L19

**Comment by radams78** [comment]
The variables angle and ramp are still not initialized in the constructor.

**Comment by samibr96** [comment]
I change in function, that I have true or false for Angle. 

I add an argument in truck, and add a value for angle = true. The name of angle is (liftbed)
