### ISSUE TITLE
CRITICAL: Instance variables not initialized in constructor

### ISSUE THREAD

**Issue by radams78** [samibr96/lab2#8]
All instance variables should be assigned a value in the constructor.

https://github.com/samibr96/lab2/blob/b16b8f5c98a18691972f05f8d4e13af1b7292a28/Transport.java#L10-L16

**Comment by radams78** [comment]
storage, truck and ramp are not initialized in the constructor.

Hint: Remove the instance variable truck. But storage and ramp should be there, and must be initialized.

**Comment by samibr96** [comment]
I Remove the instance variable truck in Transport.
